language: node_js
node_js:
  - "9"
  - "8"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - /bin/true
after-success:
  - npm run
notifications:
  email: false
