language: node_js
node_js:
  - "9"
  - "8"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - /bin/true
after-success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login repo.treescale.com
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD
    docker build
    docker push repo.treescale.com/colinskeep/ozark-login-api:latest
  fi
notifications:
  email: false
