language: node_js
node_js:
- '9'
- '8'
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
services:
- docker
cache:
  directories:
  - node_modules
install:
- npm install
script:
- xvfb-run npm run test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
  docker login repo.treescale.com -u $TREESCALE_USERNAME -p $TREESCALE_PASSWORD
  docker build -t repo.treescale.com/colinskeep/ozark-login-api .
  docker push repo.treescale.com/colinskeep/ozark-login-api:latest
  fi
notifications:
  email: false
