language: node_js
node_js:
  - "9"
  - "8"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
  - npm run build
script:
  - xvfb-run npm run test
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login repo.treescale.com
    username: $TREESCALE_USERNAME
    password: $TREESCALE_PASSWORD
    kompose up repo.treescale.com/colinskeep/ozark-login-api:latest
  fi
notifications:
  email: false
