version: "3"
services:
  app:
    container_name: ozark-login-api
    restart: always
    #build: ./
    image: colinskeep/ozark-login-api
    labels:
      kompose.volume.size: "2G"
      kompose.service.expose: "api.websmite.net"
      external-dns.alpha.kubernetes.io/hostname: "api.websmite.net"
    ports:
      - "80:9000"
    volumes:
      - .:/app
